spring.application.name=iitp-rest
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url= jdbc:postgresql://localhost:5432/iitp
spring.datasource.username= postgres
spring.datasource.password= postgres

logging.level.root=INFO

database.vehicle_sim.dbPath=db/vehicle_sim.db
database.vehicle_sim.remoteUrl=http://seoul.gaia3d.com:10217/scenarios/

sftp.host=175.197.92.213
sftp.port=10208
sftp.user=gaia3d
sftp.password=gaia3d
sftp.base-path=/home/gaia3d/iitp/data/models/

spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.jpa.hibernate.database=postgresql

# debugging - jpa n+1 problem
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# logging.level.org.hibernate.SQL=DEBUG

# optimize db access
spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.api-docs.enabled=true

# Swagger UI
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/api-docs/ui