-- ============================================================
-- 메뉴 구조 전면 개편 마이그레이션
-- ============================================================
-- 적용 전 현재 구조 확인:
--   SELECT menu_id, menu_code, name_kor, depth, sort_order, parents_id, available
--   FROM menu ORDER BY depth, sort_order, menu_id;
-- ============================================================

BEGIN;

-- ────────────────────────────────────────────────────────────
-- 0. identity 시퀀스 리셋
--    bucheon_menu_migration.sql 에서 menu_id를 명시 지정(46~51)해
--    시퀀스가 뒤처진 경우 중복 키 오류가 발생하므로 먼저 리셋
--    (GENERATED BY DEFAULT AS IDENTITY → ALTER TABLE RESTART WITH 사용)
-- ────────────────────────────────────────────────────────────
DO $$
DECLARE
    next_id bigint;
BEGIN
    SELECT MAX(menu_id) + 1 INTO next_id FROM menu;
    EXECUTE 'ALTER TABLE menu ALTER COLUMN menu_id RESTART WITH ' || next_id;
END $$;

-- ────────────────────────────────────────────────────────────
-- 1. 미구현 / 제거 대상 항목 비활성화
-- ────────────────────────────────────────────────────────────
UPDATE menu SET available = 'N' WHERE menu_id IN (
    8,   -- SCENARIO_EDIT    (편집 > 시나리오 (편집))
    18,  -- DRT_STATION
    20,  -- TRAM_STATION
    21,  -- BUS_GARAGE
    22,  -- TRAM_GARAGE
    33,  -- TRAM_PT_LINE
    41,  -- SCHEMA_DRT_STATION
    43   -- SCHEMA_TRAM_STATION
);

-- ────────────────────────────────────────────────────────────
-- 2. 신규 최상위 메뉴 "설정 (SETTINGS)" 추가
-- ────────────────────────────────────────────────────────────
INSERT INTO menu (menu_code, available, depth, language, name_en, name_kor, sort_order,
                  parents_id, root_id, created_by, created_date, last_modified_by, last_modified_date)
VALUES ('SETTINGS', 'Y', 0, 'ko-KR', 'Settings', '설정', 4,
        null, null, 'system', now(), 'system', now());

-- root_id는 자기 자신 (identity라 아직 모름 → 아래에서 업데이트)
UPDATE menu SET root_id = menu_id WHERE menu_code = 'SETTINGS' AND depth = 0;

-- ────────────────────────────────────────────────────────────
-- 3. 신규 "도로망 (ROAD)" 카테고리 추가 (편집 하위)
-- ────────────────────────────────────────────────────────────
INSERT INTO menu (menu_code, available, depth, language, name_en, name_kor, sort_order,
                  parents_id, root_id, created_by, created_date, last_modified_by, last_modified_date)
VALUES ('ROAD', 'Y', 1, 'ko-KR', 'Road Network', '도로망', 1,
        2, 2, 'system', now(), 'system', now());

-- ────────────────────────────────────────────────────────────
-- 4. 파일 메뉴 개편
-- ────────────────────────────────────────────────────────────

-- 4-1. FILE > NETWORK → IMPORT (가져오기) 로 변경
UPDATE menu SET
    menu_code  = 'IMPORT',
    name_en    = 'Import',
    name_kor   = '가져오기',
    sort_order = 1
WHERE menu_id = 4;

-- 4-2. EXPORT를 FILE 직속 depth=1 으로 승격 (sort_order=2)
UPDATE menu SET
    depth      = 1,
    parents_id = 1,
    root_id    = 1,
    sort_order = 2
WHERE menu_id = 15;  -- EXPORT

-- 4-3. SCENARIO → 시나리오 관리 (sort_order=3)
UPDATE menu SET
    name_kor   = '시나리오 관리',
    sort_order = 3
WHERE menu_id = 5;  -- SCENARIO

-- 4-4. OSM 가져오기 추가 (FILE > IMPORT 하위, sort_order=1)
--      이미 OSM_IMPORT가 있으면 SKIP
INSERT INTO menu (menu_code, available, depth, language, name_en, name_kor, sort_order,
                  parents_id, root_id, created_by, created_date, last_modified_by, last_modified_date)
SELECT 'OSM_IMPORT', 'Y', 2, 'ko-KR', 'OSM Import', 'OSM 가져오기', 1,
       4, 1, 'system', now(), 'system', now()
WHERE NOT EXISTS (SELECT 1 FROM menu WHERE menu_code = 'OSM_IMPORT');

-- 4-5. 기존 가져오기 항목 sort_order 재정렬
UPDATE menu SET sort_order = 2 WHERE menu_id = 12;  -- NETWORK_IMPORT
UPDATE menu SET sort_order = 3 WHERE menu_id = 13;  -- DEMAND_IMPORT
UPDATE menu SET sort_order = 4 WHERE menu_id = 14;  -- SIGNAL_IMPORT

-- ────────────────────────────────────────────────────────────
-- 5. 편집 메뉴 개편
-- ────────────────────────────────────────────────────────────

-- 5-1. NETWORK(16), PAVEMENT_MARKING(24) → ROAD 하위로 이동
UPDATE menu SET
    depth      = 2,
    parents_id = (SELECT menu_id FROM menu WHERE menu_code = 'ROAD'),
    root_id    = 2,
    sort_order = 1
WHERE menu_id = 16;  -- NETWORK (도로)

UPDATE menu SET
    depth      = 2,
    parents_id = (SELECT menu_id FROM menu WHERE menu_code = 'ROAD'),
    root_id    = 2,
    sort_order = 2
WHERE menu_id = 24;  -- PAVEMENT_MARKING (노면표시)

-- 5-2. FACILITY → 교통 시설물 (도로/노면표시 빠진 자리 정리, sort_order=2)
UPDATE menu SET
    name_kor   = '교통 시설물',
    name_en    = 'Traffic Facility',
    sort_order = 2
WHERE menu_id = 6;

-- 5-3. FACILITY 하위 sort_order 재정렬 (SIGNAL, SIGNAL_TOD, BUS_STATION, RAIL_STATION)
UPDATE menu SET sort_order = 1 WHERE menu_id = 23;  -- SIGNAL
UPDATE menu SET sort_order = 2 WHERE menu_id = 46;  -- SIGNAL_TOD
UPDATE menu SET sort_order = 3 WHERE menu_id = 17;  -- BUS_STATION
UPDATE menu SET sort_order = 4 WHERE menu_id = 19;  -- RAIL_STATION

-- 5-4. PT_LINE sort_order=3, 하위 항목 sort_order 정리
UPDATE menu SET sort_order = 3 WHERE menu_id = 10;  -- PT_LINE
UPDATE menu SET sort_order = 1 WHERE menu_id = 31;  -- BUS_PT_LINE
UPDATE menu SET sort_order = 2 WHERE menu_id = 48;  -- BUS_PT_LINE_WEEKDAY
UPDATE menu SET sort_order = 3 WHERE menu_id = 49;  -- BUS_PT_LINE_WEEKEND
UPDATE menu SET sort_order = 4 WHERE menu_id = 32;  -- RAIL_PT_LINE

-- 5-5. DEMAND sort_order=4, 하위 항목 sort_order 정리
UPDATE menu SET sort_order = 4 WHERE menu_id = 7;   -- DEMAND
UPDATE menu SET sort_order = 1 WHERE menu_id = 25;  -- OD_MATRIX
UPDATE menu SET sort_order = 2 WHERE menu_id = 26;  -- AGENT
UPDATE menu SET sort_order = 3 WHERE menu_id = 27;  -- PASSENGER
UPDATE menu SET sort_order = 4 WHERE menu_id = 50;  -- ROUTE
UPDATE menu SET sort_order = 5 WHERE menu_id = 51;  -- PAX_ROUTE

-- 5-6. VEHICLE sort_order=5
UPDATE menu SET sort_order = 5 WHERE menu_id = 9;   -- VEHICLE

-- ────────────────────────────────────────────────────────────
-- 6. 시뮬레이션 메뉴 개편
-- ────────────────────────────────────────────────────────────

-- 6-1. SIMULATION_CONFIG 이름 통일
UPDATE menu SET
    name_kor = '시뮬레이션 설정',
    name_en  = 'Simulation Config'
WHERE menu_id = 11;

-- 6-2. SCENARIO_SETTINGS → SIMULATION_CONFIG 하위로 이동 (sort_order=1)
UPDATE menu SET
    depth      = 2,
    parents_id = 11,
    root_id    = 3,
    sort_order = 1
WHERE menu_id = 28;  -- SCENARIO_SETTINGS

-- 6-3. 하위 sort_order 재정렬
UPDATE menu SET sort_order = 2 WHERE menu_id = 34;  -- SIMULATION_LEVEL
UPDATE menu SET sort_order = 3 WHERE menu_id = 47;  -- SIMULATION_SCENARIO

-- ────────────────────────────────────────────────────────────
-- 7. 설정 메뉴 (SETTINGS) - 스키마 설정 이동
-- ────────────────────────────────────────────────────────────

-- 7-1. SCHEMA_SETTING → SETTINGS 하위로 이동
UPDATE menu SET
    depth      = 1,
    parents_id = (SELECT menu_id FROM menu WHERE menu_code = 'SETTINGS' AND depth = 0),
    root_id    = (SELECT menu_id FROM menu WHERE menu_code = 'SETTINGS' AND depth = 0),
    sort_order = 1
WHERE menu_id = 38;  -- SCHEMA_SETTING

-- 7-2. 스키마 하위 항목 root_id 업데이트
UPDATE menu SET
    root_id = (SELECT menu_id FROM menu WHERE menu_code = 'SETTINGS' AND depth = 0)
WHERE menu_id IN (39, 40, 41, 42, 43, 44);

-- 7-3. 스키마 항목 sort_order 정리 (활성 항목만)
UPDATE menu SET sort_order = 1 WHERE menu_id = 39;  -- SCHEMA_NETWORK
UPDATE menu SET sort_order = 2 WHERE menu_id = 40;  -- SCHEMA_BUS_STATION
UPDATE menu SET sort_order = 3 WHERE menu_id = 42;  -- SCHEMA_RAIL_STATION
UPDATE menu SET sort_order = 4 WHERE menu_id = 44;  -- SCHEMA_PAVEMENT_MARKING

-- ────────────────────────────────────────────────────────────
-- 확인 쿼리 (COMMIT 전에 실행해보세요)
-- ────────────────────────────────────────────────────────────
-- SELECT m.menu_id, m.menu_code, m.name_kor, m.depth, m.sort_order, m.available,
--        p.name_kor AS parent_kor
-- FROM menu m
-- LEFT JOIN menu p ON m.parents_id = p.menu_id
-- WHERE m.available != 'N'
-- ORDER BY m.depth, m.sort_order, m.menu_id;

COMMIT;

-- ── 2026-06-11: OSM_IMPORT → KTDB_IMPORT, SUMO_IMPORT → OSM_IMPORT 리네임 ──
UPDATE menu SET menu_code = 'KTDB_IMPORT', name_en = 'KTDB Import', name_kor = '표준 노드링크 가져오기'
WHERE menu_code = 'OSM_IMPORT';

UPDATE menu SET menu_code = 'OSM_IMPORT', name_en = 'OSM Import', name_kor = 'OSM 가져오기'
WHERE menu_code = 'SUMO_IMPORT';

-- ── 2026-06-15: 메뉴 구조 개선 ──
-- 1. IMPORT 순서: KTDB → OSM → 네트워크 → 수요 → 신호
UPDATE menu SET sort_order = 1 WHERE menu_code = 'KTDB_IMPORT';
UPDATE menu SET sort_order = 2 WHERE menu_code = 'OSM_IMPORT';
UPDATE menu SET sort_order = 3 WHERE menu_id = 12;  -- NETWORK_IMPORT
UPDATE menu SET sort_order = 4 WHERE menu_id = 13;  -- DEMAND_IMPORT
UPDATE menu SET sort_order = 5 WHERE menu_id = 14;  -- SIGNAL_IMPORT

-- 2. SIMULATION 평탄화: SIMULATION_CONFIG 중간 레벨 제거
UPDATE menu SET available = 'N' WHERE menu_id = 11;  -- SIMULATION_CONFIG
UPDATE menu SET depth = 1, parents_id = 3, sort_order = 1 WHERE menu_id = 34;  -- SIMULATION_LEVEL
UPDATE menu SET depth = 1, parents_id = 3, sort_order = 2 WHERE menu_id = 47;  -- SIMULATION_SCENARIO

-- 3. DEMAND 미구현 항목 제거
UPDATE menu SET available = 'N' WHERE menu_id = 50;  -- ROUTE
UPDATE menu SET available = 'N' WHERE menu_id = 51;  -- PAX_ROUTE

-- ── 2026-07-09: 네트워크 임포트 메뉴 정리 ─────────────────────────────────────
-- KTDB/OSM/NETWORK 임포트는 FileImportModal(헤더 파일>가져오기 KTDB/OSM/파일 탭)로 통합.
-- 헤더가 FILE 루트 메뉴 트리를 렌더하지 않아(FileDropdown 대체) 도달 불가였던
-- 구 메뉴 모달(KtdbImportModal/OsmImportModal/NetworkImportModal)은 프론트에서 삭제됨.
UPDATE menu SET available = 'N' WHERE menu_code IN ('KTDB_IMPORT', 'OSM_IMPORT', 'NETWORK_IMPORT');

-- ── 2026-07-21: NextSim 필수 흐름 기준 메뉴 재구성 ──────────────────────────
-- NEXTSIM_DATA_STRUCTURE.md 기준으로 실제 NextSim 입력에 대응하지 않거나
-- 구현이 없는 메뉴를 정리하고, FACILITY 그룹을 NextSim 입력 단위(network/
-- signal/대중교통 정류장)에 맞춰 3분할.

-- 1. 고아/미구현 메뉴 삭제
-- AGENT: NextSim 데이터 구조 문서 전체에 대응 개념이 없고 프론트/백엔드
-- 어디서도 구현되지 않음.
DELETE FROM menu WHERE menu_code = 'AGENT';

-- SCENARIO_EDIT / SCENARIO_SETTINGS: 코드베이스 전체에서 참조 0건인 고아 메뉴.
DELETE FROM menu WHERE menu_code = 'SCENARIO_SETTINGS';
DELETE FROM menu WHERE menu_code = 'SCENARIO_EDIT';

-- FILE 하위 NETWORK(4)/SCENARIO(5) 서브트리: HeaderMenu.tsx의 파일 드롭다운이
-- DB 메뉴 트리를 렌더링하지 않고 자체 하드코딩(FILE_ITEMS)을 쓰므로 구조적으로
-- 도달 불가능한 죽은 row. menu_code='NETWORK'가 depth 1(id4)과 depth 2(id16,
-- 도로)에 중복 존재해 menu_id로 지정.
DELETE FROM menu WHERE menu_id IN (52, 53, 12, 15, 13, 14);
DELETE FROM menu WHERE menu_id = 4;  -- FILE > 네트워크
DELETE FROM menu WHERE menu_id = 5;  -- FILE > 시나리오

-- 2. 자동 생성 산출물 메뉴 삭제 / 미완성이나 편집 필요한 원본 데이터는 유지
-- ROUTE(차량 경로)/PAX_ROUTE(승객 경로): Route.json/PaxRoute.json은 문서상
-- "생성 필요" — route-generator가 network/odmatrix/mode로부터 자동 파생하는
-- 산출물이라 사용자가 편집할 원본이 아님. 편집 UI 불필요 → 삭제.
DELETE FROM menu WHERE menu_id IN (50, 51);

-- PASSENGER: passenger.xml(선택)은 OD Matrix와 대칭되는 승객 OD 수요 "원본
-- 입력"이지 자동 파생 산출물이 아님. PassengerController/Service가 없어
-- NextSimRunner가 실행 시 항상 빈 <od_pax/>만 기록하는 미완성 상태이지만,
-- 편집이 필요한 데이터이므로 메뉴는 유지하고 향후 구현 대상으로 남긴다.

-- DRT_STATION/TRAM_STATION/BUS_GARAGE/TRAM_GARAGE/TRAM_PT_LINE: NextSim 데이터
-- 구조에 대응 개념이 없고, DB menuCode와 정확히 일치하는 apiConfig/store 배선도
-- 없어 클릭해도 저장되지 않음. 자동 산출물은 아니지만 NextSim 기반 재구성
-- 범위에서 구현 여부 판단 보류 → 우선 숨김.
UPDATE menu SET available = 'N'
WHERE menu_code IN ('DRT_STATION', 'TRAM_STATION', 'BUS_GARAGE', 'TRAM_GARAGE', 'TRAM_PT_LINE');

-- 3. FACILITY(6) → 도로망 / 신호 / 대중교통 정류장 3분할
UPDATE menu SET menu_code = 'ROAD_NETWORK_GROUP', name_en = 'Road Network', name_kor = '도로망', sort_order = 1
WHERE menu_id = 6;
UPDATE menu SET sort_order = 1 WHERE menu_id = 16;  -- NETWORK(도로)
UPDATE menu SET sort_order = 2 WHERE menu_id = 24;  -- PAVEMENT_MARKING

INSERT INTO menu (menu_code, available, depth, language, name_en, name_kor, sort_order, parents_id, root_id, created_by, created_date)
VALUES ('SIGNAL_GROUP', 'Y', 1, 'ko-KR', 'Signal', '신호', 2, 2, 2, 'system', now());
UPDATE menu SET parents_id = (SELECT menu_id FROM menu WHERE menu_code = 'SIGNAL_GROUP'), root_id = 2, sort_order = 1 WHERE menu_id = 23;  -- SIGNAL
UPDATE menu SET parents_id = (SELECT menu_id FROM menu WHERE menu_code = 'SIGNAL_GROUP'), root_id = 2, sort_order = 2 WHERE menu_id = 46;  -- SIGNAL_TOD

INSERT INTO menu (menu_code, available, depth, language, name_en, name_kor, sort_order, parents_id, root_id, created_by, created_date)
VALUES ('PT_STATION_GROUP', 'Y', 1, 'ko-KR', 'Transit Stations', '대중교통 정류장', 3, 2, 2, 'system', now());
UPDATE menu SET parents_id = (SELECT menu_id FROM menu WHERE menu_code = 'PT_STATION_GROUP'), root_id = 2, sort_order = 1 WHERE menu_id = 17;  -- BUS_STATION
UPDATE menu SET parents_id = (SELECT menu_id FROM menu WHERE menu_code = 'PT_STATION_GROUP'), root_id = 2, sort_order = 2 WHERE menu_id = 19;  -- RAIL_STATION
UPDATE menu SET parents_id = (SELECT menu_id FROM menu WHERE menu_code = 'PT_STATION_GROUP'), root_id = 2, sort_order = 3 WHERE menu_id = 18;  -- DRT_STATION (숨김)
UPDATE menu SET parents_id = (SELECT menu_id FROM menu WHERE menu_code = 'PT_STATION_GROUP'), root_id = 2, sort_order = 4 WHERE menu_id = 20;  -- TRAM_STATION (숨김)
UPDATE menu SET parents_id = (SELECT menu_id FROM menu WHERE menu_code = 'PT_STATION_GROUP'), root_id = 2, sort_order = 5 WHERE menu_id = 21;  -- BUS_GARAGE (숨김)
UPDATE menu SET parents_id = (SELECT menu_id FROM menu WHERE menu_code = 'PT_STATION_GROUP'), root_id = 2, sort_order = 6 WHERE menu_id = 22;  -- TRAM_GARAGE (숨김)

-- EDIT(2) 하위 나머지 그룹 sort_order 재정렬
UPDATE menu SET sort_order = 4 WHERE menu_id = 7;   -- DEMAND
UPDATE menu SET sort_order = 5 WHERE menu_id = 9;   -- VEHICLE
UPDATE menu SET sort_order = 6 WHERE menu_id = 10;  -- PT_LINE

-- ── 2026-07-21 (추가): DRT/TRAM 스키마 메뉴 숨김 ────────────────────────────
-- SCHEMA_DRT_STATION/SCHEMA_TRAM_STATION: propertyFormSchema.ts에 layer 키가
-- 없어 SchemaSetting.tsx가 빈 화면만 띄움(getSchemaByLayerName(null)). DRT/TRAM
-- 시설물 편집 메뉴를 숨긴 것과 일관되게 스키마 편집 쪽도 숨김.
UPDATE menu SET available = 'N' WHERE menu_code IN ('SCHEMA_DRT_STATION', 'SCHEMA_TRAM_STATION');

-- ── 2026-07-21 (추가): SIMULATION 최상위 메뉴 제거, 편집 하위로 흡수 ─────────
-- SIMULATION_LEVEL(mode.xml)은 propertyFormSchema가 빈 스텁이고 App.tsx 렌더
-- 분기에도 대응 케이스가 없어 클릭해도 아무 화면도 안 뜨는 죽은 메뉴였음(숨김
-- 처리). SIMULATION_CONFIG는 이미 이전 마이그레이션에서 평탄화되어 자식 없이
-- 방치된 사문화 노드라 삭제. 남는 유일한 실동작 항목 SIMULATION_SCENARIO 하나
-- 때문에 최상위 메뉴를 유지할 이유가 없어 EDIT 하위로 흡수하고 SIMULATION
-- 최상위 자체를 제거.
UPDATE menu SET parents_id = 2, depth = 1, root_id = 2, sort_order = 7 WHERE menu_id = 47;  -- SIMULATION_SCENARIO
UPDATE menu SET parents_id = 2, depth = 1, root_id = 2, sort_order = 8, available = 'N' WHERE menu_id = 34;  -- SIMULATION_LEVEL
DELETE FROM menu WHERE menu_id = 11;  -- SIMULATION_CONFIG (자식 없는 사문화 노드)
DELETE FROM menu WHERE menu_id = 3;   -- SIMULATION 최상위 메뉴
