-- 2) 테이블 생성
CREATE TABLE public.menu
(
    menu_id            bigint generated by default as identity
        primary key,
    menu_code           VARCHAR(255)                                        NOT NULL,
    available           CHAR,
    access_role        varchar(255),
    depth               INTEGER,
    language            VARCHAR(255),
    name_en             VARCHAR(255),
    name_kor            VARCHAR(255),
    sort_order          INTEGER,
    parents_id          BIGINT CONSTRAINT fk_menu_parents REFERENCES public.menu(menu_id) ON DELETE SET NULL,
    root_id             BIGINT CONSTRAINT fk_menu_root    REFERENCES public.menu(menu_id) ON DELETE SET NULL,

    created_by          VARCHAR(255),
    created_date        TIMESTAMP(6) WITH TIME ZONE,
    last_modified_by    VARCHAR(255),
    last_modified_date  TIMESTAMP(6) WITH TIME ZONE
);

ALTER TABLE public.menu
    OWNER TO postgres;

-- 3) 기본 데이터 INSERT (1~35번까지)
INSERT INTO public.menu
( menu_code
, available
, depth
, language
, name_en
, name_kor
, sort_order
, parents_id
, root_id
, created_by
, created_date
, last_modified_by
, last_modified_date
)
VALUES
    ('FILE',               'Y', 0, 'ko-KR', 'File',                        '파일',                   1, NULL, NULL, 'system', NOW(), 'system', NOW()),
    ('EDIT',               'Y', 0, 'ko-KR', 'Edit',                        '편집',                   2, NULL, NULL, 'system', NOW(), 'system', NOW()),
    ('SIMULATION',         'Y', 0, 'ko-KR', 'Simulation',                  '시뮬레이션',             3, NULL, NULL, 'system', NOW(), 'system', NOW()),
    ( 'NETWORK',            'Y', 1, 'ko-KR', 'Network',                     '네트워크',               1,    1,    1,    'system', NOW(), 'system', NOW()),
    ('SCENARIO',           'Y', 1, 'ko-KR', 'Scenario',                    '시나리오',               2,    1,    1,    'system', NOW(), 'system', NOW()),
    ('FACILITY',           'Y', 1, 'ko-KR', 'Facility',                    '시설물',                 1,    2,    2,    'system', NOW(), 'system', NOW()),
    ('DEMAND',             'Y', 1, 'ko-KR', 'Demand',                      '수요',                   2,    2,    2,    'system', NOW(), 'system', NOW()),
    ('SCENARIO_EDIT',      'Y', 1, 'ko-KR', 'Scenario (Edit)',             '시나리오 (편집)',        3,    2,    2,    'system', NOW(), 'system', NOW()),
    ( 'VEHICLE',            'Y', 1, 'ko-KR', 'Vehicle',                     '교통수단',               4,    2,    2,    'system', NOW(), 'system', NOW()),
    ('PT_LINE',            'Y', 1, 'ko-KR', 'Public Transport Line',       '대중교통 노선',          5,    2,    2,    'system', NOW(), 'system', NOW()),
    ('SIMULATION_CONFIG',  'Y', 1, 'ko-KR', 'Simulation Config',           '시뮬레이션 설정',        1,    3,    3,    'system', NOW(), 'system', NOW()),
    ('NETWORK_IMPORT',     'Y', 2, 'ko-KR', 'Network Import',              '네트워크 파일 가져오기', 1,    4,    1,    'system', NOW(), 'system', NOW()),
    ( 'DEMAND_IMPORT',      'Y', 2, 'ko-KR', 'Demand Import',               '수요 파일 가져오기',     2,    4,    1,    'system', NOW(), 'system', NOW()),
    ('SIGNAL_IMPORT',      'Y', 2, 'ko-KR', 'Signal Import',               '신호 파일 가져오기',     3,    4,    1,    'system', NOW(), 'system', NOW()),
    ('EXPORT',             'Y', 2, 'ko-KR', 'Export',                      '내보내기',              4,    4,    1,    'system', NOW(), 'system', NOW()),
    ('ROAD',               'Y', 2, 'ko-KR', 'Road',                        '도로',                   1,    6,    2,    'system', NOW(), 'system', NOW()),
    ('CONNECTION',         'Y', 2, 'ko-KR', 'Connection',                  '커넥션',                 2,    6,    2,    'system', NOW(), 'system', NOW()),
    ('PT_BUS_STATION',     'Y', 2, 'ko-KR', 'Public Transport Bus Station','대중교통(BUS) 정류장',    3,    6,    2,    'system', NOW(), 'system', NOW()),
    ('PT_DRT_STATION',     'Y', 2, 'ko-KR', 'Public Transport DRT Station','대중교통(DRT) 정류장',    4,    6,    2,    'system', NOW(), 'system', NOW()),
    ('PT_RAIL_STATION',    'Y', 2, 'ko-KR', 'Public Transport Rail Station','대중교통(RAIL) 정류장',   5,    6,    2,    'system', NOW(), 'system', NOW()),
    ( 'PT_TRAM_STATION',    'Y', 2, 'ko-KR', 'Public Transport TRAM Station','대중교통(TRAM) 정류장',  6,    6,    2,    'system', NOW(), 'system', NOW()),
    ('PT_BUS_GARAGE',      'Y', 2, 'ko-KR', 'Public Transport Bus Garage','대중교통(BUS) 차고지',    7,    6,    2,    'system', NOW(), 'system', NOW()),
    ( 'PT_TRAM_GARAGE',     'Y', 2, 'ko-KR', 'Public Transport TRAM Garage','대중교통(TRAM) 차고지', 8,    6,    2,    'system', NOW(), 'system', NOW()),
    ('SIGNAL',             'Y', 2, 'ko-KR', 'Signal',                      '신호등',                 9,    6,    2,    'system', NOW(), 'system', NOW()),
    ('PAVEMENT_MARKING',   'Y', 2, 'ko-KR', 'Pavement Marking',            '노면표시',              10,   6,    2,    'system', NOW(), 'system', NOW()),
    ( 'OD_MATRIX',          'Y', 2, 'ko-KR', 'OD Matrix',                   'OD Matrix 설정',         1,    7,    2,    'system', NOW(), 'system', NOW()),
    ('AGENT',              'Y', 2, 'ko-KR', 'Agent',                       'AGENT 설정',            2,    7,    2,    'system', NOW(), 'system', NOW()),
    ('PASSENGER',          'Y', 2, 'ko-KR', 'Passenger',                   'PASSENGER 설정',        3,    7,    2,    'system', NOW(), 'system', NOW()),
    ('SCENARIO_SETTINGS',  'Y', 2, 'ko-KR', 'Scenario Settings',           '시나리오 설정',          1,    8,    2,    'system', NOW(), 'system', NOW()),
    ('VEHICLE_TYPE',       'Y', 2, 'ko-KR', 'Vehicle Type',                '교통수단 유형',           1,    9,    2,    'system', NOW(), 'system', NOW()),
    ('VEHICLE_MODEL',      'Y', 2, 'ko-KR', 'Vehicle Model',               '교통수단 2D&3D 모델',     2,    9,    2,    'system', NOW(), 'system', NOW()),
    ('BUS_PT_LINE',        'Y', 2, 'ko-KR', 'Bus Public Transport Line',   '대중교통(BUS) 노선',      1,   10,    2,    'system', NOW(), 'system', NOW()),
    ('RAIL_PT_LINE',       'Y', 2, 'ko-KR', 'Rail Public Transport Line',  '대중교통(RAIL) 노선',     2,   10,    2,    'system', NOW(), 'system', NOW()),
    ('TRAM_PT_LINE',       'Y', 2, 'ko-KR', 'Tram Public Transport Line',  '대중교통(TRAM) 노선',     3,   10,    2,    'system', NOW(), 'system', NOW()),
    ( 'SIMULATION_LEVEL',   'Y', 2, 'ko-KR', 'Simulation Level',            '시뮬레이션 레벨 설정',     1,   11,    3,    'system', NOW(), 'system', NOW());