create table station
(
    id      bigint generated by default as identity
        primary key,
    geojson text,
    name    varchar(255)
);

alter table station
    owner to postgres;

-- auto-generated definition
create sequence station_id_seq;

alter sequence station_id_seq owner to postgres;

alter sequence station_id_seq owned by station.id;

INSERT INTO public.station
VALUES (1, '{
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "id": 30011458, "linkRef": "20000573", "laneRef": 3, "offset": 56.02, "parkingLots": 2, "transitMode": "bus", "type": "side", "address": null }, "geometry": { "type": "Point", "coordinates": [ 127.38613973, 36.37684553 ] } },
{ "type": "Feature", "properties": { "id": 30011459, "linkRef": "20000572", "laneRef": 2, "offset": 211.21, "parkingLots": 2, "transitMode": "bus", "type": "side", "address": null }, "geometry": { "type": "Point", "coordinates": [ 127.38734165, 36.37698175 ] } },
{ "type": "Feature", "properties": { "id": 30011460, "linkRef": "20000624", "laneRef": 2, "offset": 62.48, "parkingLots": 2, "transitMode": "bus", "type": "side", "address": null }, "geometry": { "type": "Point", "coordinates": [ 127.39020732, 36.3766117 ] } },
{ "type": "Feature", "properties": { "id": 30011463, "linkRef": "20001486", "laneRef": 3, "offset": 49.5, "parkingLots": 2, "transitMode": "bus", "type": "side", "address": null }, "geometry": { "type": "Point", "coordinates": [ 127.39051933, 36.37627207 ] } },
{ "type": "Feature", "properties": { "id": 30011465, "linkRef": "20001169", "laneRef": 5, "offset": 69.22, "parkingLots": 2, "transitMode": "bus", "type": "side", "address": null }, "geometry": { "type": "Point", "coordinates": [ 127.39506703, 36.37568901 ] } },
{ "type": "Feature", "properties": { "id": 30011466, "linkRef": "20001148", "laneRef": 5, "offset": 44.48, "parkingLots": 2, "transitMode": "bus", "type": "side", "address": null }, "geometry": { "type": "Point", "coordinates": [ 127.39396855, 36.37610199 ] } },
{ "type": "Feature", "properties": { "id": 30011467, "linkRef": "20001177", "laneRef": 5, "offset": 98.98, "parkingLots": 2, "transitMode": "bus", "type": "side", "address": null }, "geometry": { "type": "Point", "coordinates": [ 127.3962934, 36.37579178 ] } },
{ "type": "Feature", "properties": { "id": 30011468, "linkRef": "20000417", "laneRef": 1, "offset": 18.05, "parkingLots": 2, "transitMode": "bus", "type": "side", "address": null }, "geometry": { "type": "Point", "coordinates": [ 127.3838544, 36.37620568 ] } },
{ "type": "Feature", "properties": { "id": 30011470, "linkRef": "20000414", "laneRef": 1, "offset": 108.88, "parkingLots": 2, "transitMode": "bus", "type": "side", "address": null }, "geometry": { "type": "Point", "coordinates": [ 127.3837741, 36.37633215 ] } },
{ "type": "Feature", "properties": { "id": 30011471, "linkRef": "20000446", "laneRef": 3, "offset": 29.93, "parkingLots": 2, "transitMode": "bus", "type": "side", "address": null }, "geometry": { "type": "Point", "coordinates": [ 127.38496334, 36.37500334 ] } },
{ "type": "Feature", "properties": { "id": 30011474, "linkRef": "20000590", "laneRef": 5, "offset": 70.28, "parkingLots": 2, "transitMode": "bus", "type": "side", "address": null }, "geometry": { "type": "Point", "coordinates": [ 127.38822997, 36.37627806 ] } },
{ "type": "Feature", "properties": { "id": 30011475, "linkRef": "20001471", "laneRef": 4, "offset": 40.37, "parkingLots": 2, "transitMode": "bus", "type": "side", "address": null }, "geometry": { "type": "Point", "coordinates": [ 127.38784991, 36.37614771 ] } },
{ "type": "Feature", "properties": { "id": 30011477, "linkRef": "20000882", "laneRef": 2, "offset": 46.01, "parkingLots": 2, "transitMode": "bus", "type": "side", "address": null }, "geometry": { "type": "Point", "coordinates": [ 127.39195759, 36.37490687 ] } },
{ "type": "Feature", "properties": { "id": 30011478, "linkRef": "20000883", "laneRef": 2, "offset": 47.15, "parkingLots": 2, "transitMode": "bus", "type": "side", "address": null }, "geometry": { "type": "Point", "coordinates": [ 127.39174258, 36.37453692 ] } },
{ "type": "Feature", "properties": { "id": 30011479, "linkRef": "20001507", "laneRef": 2, "offset": 70.27, "parkingLots": 2, "transitMode": "bus", "type": "side", "address": null }, "geometry": { "type": "Point", "coordinates": [ 127.38320968, 36.37364396 ] } },
{ "type": "Feature", "properties": { "id": 30011480, "linkRef": "20000456", "laneRef": 2, "offset": 91.58, "parkingLots": 2, "transitMode": "bus", "type": "side", "address": null }, "geometry": { "type": "Point", "coordinates": [ 127.38329468, 36.37346534 ] } },
{ "type": "Feature", "properties": { "id": 30011481, "linkRef": "20000467", "laneRef": 1, "offset": 42.3, "parkingLots": 2, "transitMode": "bus", "type": "side", "address": null }, "geometry": { "type": "Point", "coordinates": [ 127.38279243, 36.37155335 ] } },
{ "type": "Feature", "properties": { "id": 30011483, "linkRef": "20000472", "laneRef": 1, "offset": 13.32, "parkingLots": 2, "transitMode": "bus", "type": "side", "address": null }, "geometry": { "type": "Point", "coordinates": [ 127.38289447, 36.37159808 ] } },
{ "type": "Feature", "properties": { "id": 30011484, "linkRef": "20000964", "laneRef": 2, "offset": 31.43, "parkingLots": 2, "transitMode": "bus", "type": "side", "address": null }, "geometry": { "type": "Point", "coordinates": [ 127.39168794, 36.37364119 ] } },
{ "type": "Feature", "properties": { "id": 30011486, "linkRef": "20000962", "laneRef": 1, "offset": 81.47, "parkingLots": 2, "transitMode": "bus", "type": "side", "address": null }, "geometry": { "type": "Point", "coordinates": [ 127.39150758, 36.37338312 ] } },
{ "type": "Feature", "properties": { "id": 30011491, "linkRef": "20001053", "laneRef": 1, "offset": 15.1, "parkingLots": 2, "transitMode": "bus", "type": "side", "address": null }, "geometry": { "type": "Point", "coordinates": [ 127.39105169, 36.37057624 ] } },
{ "type": "Feature", "properties": { "id": 30011492, "linkRef": "20001051", "laneRef": 2, "offset": 39.49, "parkingLots": 2, "transitMode": "bus", "type": "side", "address": null }, "geometry": { "type": "Point", "coordinates": [ 127.39080964, 36.37003066 ] } },
{ "type": "Feature", "properties": { "id": 30011495, "linkRef": "20001134", "laneRef": 3, "offset": 13.52, "parkingLots": 2, "transitMode": "bus", "type": "side", "address": null }, "geometry": { "type": "Point", "coordinates": [ 127.39122056, 36.36942681 ] } },
{ "type": "Feature", "properties": { "id": 30011496, "linkRef": "20001132", "laneRef": 3, "offset": 65.4, "parkingLots": 2, "transitMode": "bus", "type": "side", "address": null }, "geometry": { "type": "Point", "coordinates": [ 127.39151754, 36.3692259 ] } },
{ "type": "Feature", "properties": { "id": 30011497, "linkRef": "20001403", "laneRef": 2, "offset": 42.72, "parkingLots": 2, "transitMode": "bus", "type": "side", "address": null }, "geometry": { "type": "Point", "coordinates": [ 127.39377103, 36.36906214 ] } },
{ "type": "Feature", "properties": { "id": 30011498, "linkRef": "20001402", "laneRef": 2, "offset": 40.03, "parkingLots": 2, "transitMode": "bus", "type": "side", "address": null }, "geometry": { "type": "Point", "coordinates": [ 127.39405829, 36.36890471 ] } },
{ "type": "Feature", "properties": { "id": 30011502, "linkRef": "20001429", "laneRef": 2, "offset": 29.57, "parkingLots": 2, "transitMode": "bus", "type": "side", "address": null }, "geometry": { "type": "Point", "coordinates": [ 127.39602065, 36.37010025 ] } },
{ "type": "Feature", "properties": { "id": 30011503, "linkRef": "20001435", "laneRef": 2, "offset": 0.57, "parkingLots": 2, "transitMode": "bus", "type": "side", "address": null }, "geometry": { "type": "Point", "coordinates": [ 127.39575075, 36.36930904 ] } },
{ "type": "Feature", "properties": { "id": 30011504, "linkRef": "20001522", "laneRef": 2, "offset": 37.86, "parkingLots": 2, "transitMode": "bus", "type": "side", "address": null }, "geometry": { "type": "Point", "coordinates": [ 127.39626782, 36.37189364 ] } },
{ "type": "Feature", "properties": { "id": 30011505, "linkRef": "20001307", "laneRef": 1, "offset": 94.75, "parkingLots": 2, "transitMode": "bus", "type": "side", "address": null }, "geometry": { "type": "Point", "coordinates": [ 127.39642503, 36.37209994 ] } }
]
}
', 'station-test2');

INSERT INTO public.station
VALUES (2,
        '{
          "type": "FeatureCollection",
          "crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
          "features": [
            {
              "type": "Feature",
              "properties": {
                "id": 30011458,
                "linkRef": "20000573",
                "laneRef": 3,
                "offset": 56.02,
                "parkingLots": 2,
                "transitMode": "bus",
                "type": "side",
                "address": null
              },
              "geometry": {
                "type": "Point",
                "coordinates": [126.7556534421, 37.5055742225]
              }
            },
            {
              "type": "Feature",
              "properties": {
                "id": 30011459,
                "linkRef": "20000572",
                "laneRef": 2,
                "offset": 211.21,
                "parkingLots": 2,
                "transitMode": "bus",
                "type": "side",
                "address": null
              },
              "geometry": {
                "type": "Point",
                "coordinates": [126.7557192762, 37.5058507771]
              }
            },
            {
              "type": "Feature",
              "properties": {
                "id": 30011460,
                "linkRef": "20000624",
                "laneRef": 2,
                "offset": 62.48,
                "parkingLots": 2,
                "transitMode": "bus",
                "type": "side",
                "address": null
              },
              "geometry": {
                "type": "Point",
                "coordinates": [126.7610112888, 37.5051757141]
              }
            },
            {
              "type": "Feature",
              "properties": {
                "id": 30011463,
                "linkRef": "20001486",
                "laneRef": 3,
                "offset": 49.5,
                "parkingLots": 2,
                "transitMode": "bus",
                "type": "side",
                "address": null
              },
              "geometry": {
                "type": "Point",
                "coordinates": [126.7611223840, 37.5048721816]
              }
            },
            {
              "type": "Feature",
              "properties": {
                "id": 30011465,
                "linkRef": "20001169",
                "laneRef": 5,
                "offset": 69.22,
                "parkingLots": 2,
                "transitMode": "bus",
                "type": "side",
                "address": null
              },
              "geometry": {
                "type": "Point",
                "coordinates": [126.7671032162, 37.5041474433]
              }
            },
            {
              "type": "Feature",
              "properties": {
                "id": 30011466,
                "linkRef": "20001148",
                "laneRef": 5,
                "offset": 44.48,
                "parkingLots": 2,
                "transitMode": "bus",
                "type": "side",
                "address": null
              },
              "geometry": {
                "type": "Point",
                "coordinates": [126.7659624189, 37.5044687159]
              }
            },
            {
              "type": "Feature",
              "properties": {
                "id": 30011467,
                "linkRef": "20001177",
                "laneRef": 5,
                "offset": 98.98,
                "parkingLots": 2,
                "transitMode": "bus",
                "type": "side",
                "address": null
              },
              "geometry": {
                "type": "Point",
                "coordinates": [126.7682926343, 37.5041639699]
              }
            },
            {
              "type": "Feature",
              "properties": {
                "id": 30011468,
                "linkRef": "20000417",
                "laneRef": 1,
                "offset": 18.05,
                "parkingLots": 2,
                "transitMode": "bus",
                "type": "side",
                "address": null
              },
              "geometry": {
                "type": "Point",
                "coordinates": [126.7528375582, 37.5044823458]
              }
            },
            {
              "type": "Feature",
              "properties": {
                "id": 30011470,
                "linkRef": "20000414",
                "laneRef": 1,
                "offset": 108.88,
                "parkingLots": 2,
                "transitMode": "bus",
                "type": "side",
                "address": null
              },
              "geometry": {
                "type": "Point",
                "coordinates": [126.7527333217, 37.5045195983]
              }
            },
            {
              "type": "Feature",
              "properties": {
                "id": 30011471,
                "linkRef": "20000446",
                "laneRef": 3,
                "offset": 29.93,
                "parkingLots": 2,
                "transitMode": "bus",
                "type": "side",
                "address": null
              },
              "geometry": {
                "type": "Point",
                "coordinates": [126.7547432169, 37.5031197948]
              }
            },
            {
              "type": "Feature",
              "properties": {
                "id": 30011474,
                "linkRef": "20000590",
                "laneRef": 5,
                "offset": 70.28,
                "parkingLots": 2,
                "transitMode": "bus",
                "type": "side",
                "address": null
              },
              "geometry": {
                "type": "Point",
                "coordinates": [126.7583447952, 37.5048272466]
              }
            },
            {
              "type": "Feature",
              "properties": {
                "id": 30011475,
                "linkRef": "20001471",
                "laneRef": 4,
                "offset": 40.37,
                "parkingLots": 2,
                "transitMode": "bus",
                "type": "side",
                "address": null
              },
              "geometry": {
                "type": "Point",
                "coordinates": [126.7580765855, 37.5047836417]
              }
            },
            {
              "type": "Feature",
              "properties": {
                "id": 30011477,
                "linkRef": "20000882",
                "laneRef": 2,
                "offset": 46.01,
                "parkingLots": 2,
                "transitMode": "bus",
                "type": "side",
                "address": null
              },
              "geometry": {
                "type": "Point",
                "coordinates": [126.7630993157, 37.5030232305]
              }
            },
            {
              "type": "Feature",
              "properties": {
                "id": 30011478,
                "linkRef": "20000883",
                "laneRef": 2,
                "offset": 47.15,
                "parkingLots": 2,
                "transitMode": "bus",
                "type": "side",
                "address": null
              },
              "geometry": {
                "type": "Point",
                "coordinates": [126.7629372001, 37.5026962525]
              }
            },
            {
              "type": "Feature",
              "properties": {
                "id": 30011479,
                "linkRef": "20001507",
                "laneRef": 2,
                "offset": 70.27,
                "parkingLots": 2,
                "transitMode": "bus",
                "type": "side",
                "address": null
              },
              "geometry": {
                "type": "Point",
                "coordinates": [126.7521046341, 37.5015126888]
              }
            },
            {
              "type": "Feature",
              "properties": {
                "id": 30011480,
                "linkRef": "20000456",
                "laneRef": 2,
                "offset": 91.58,
                "parkingLots": 2,
                "transitMode": "bus",
                "type": "side",
                "address": null
              },
              "geometry": {
                "type": "Point",
                "coordinates": [126.7522217454, 37.5014985841]
              }
            },
            {
              "type": "Feature",
              "properties": {
                "id": 30011481,
                "linkRef": "20000467",
                "laneRef": 1,
                "offset": 42.3,
                "parkingLots": 2,
                "transitMode": "bus",
                "type": "side",
                "address": null
              },
              "geometry": {
                "type": "Point",
                "coordinates": [126.7515771138, 37.4989103944]
              }
            },
            {
              "type": "Feature",
              "properties": {
                "id": 30011483,
                "linkRef": "20000472",
                "laneRef": 1,
                "offset": 13.32,
                "parkingLots": 2,
                "transitMode": "bus",
                "type": "side",
                "address": null
              },
              "geometry": {
                "type": "Point",
                "coordinates": [126.7516221310, 37.4987362995]
              }
            },
            {
              "type": "Feature",
              "properties": {
                "id": 30011484,
                "linkRef": "20000964",
                "laneRef": 2,
                "offset": 31.43,
                "parkingLots": 2,
                "transitMode": "bus",
                "type": "side",
                "address": null
              },
              "geometry": {
                "type": "Point",
                "coordinates": [126.7627058587, 37.5011857049]
              }
            },
            {
              "type": "Feature",
              "properties": {
                "id": 30011486,
                "linkRef": "20000962",
                "laneRef": 1,
                "offset": 81.47,
                "parkingLots": 2,
                "transitMode": "bus",
                "type": "side",
                "address": null
              },
              "geometry": {
                "type": "Point",
                "coordinates": [126.7625833977, 37.5010878251]
              }
            },
            {
              "type": "Feature",
              "properties": {
                "id": 30011491,
                "linkRef": "20001053",
                "laneRef": 1,
                "offset": 15.1,
                "parkingLots": 2,
                "transitMode": "bus",
                "type": "side",
                "address": null
              },
              "geometry": {
                "type": "Point",
                "coordinates": [126.7619709981, 37.4975049969]
              }
            },
            {
              "type": "Feature",
              "properties": {
                "id": 30011492,
                "linkRef": "20001051",
                "laneRef": 2,
                "offset": 39.49,
                "parkingLots": 2,
                "transitMode": "bus",
                "type": "side",
                "address": null
              },
              "geometry": {
                "type": "Point",
                "coordinates": [126.7618168322, 37.4973710082]
              }
            },
            {
              "type": "Feature",
              "properties": {
                "id": 30011495,
                "linkRef": "20001134",
                "laneRef": 3,
                "offset": 13.52,
                "parkingLots": 2,
                "transitMode": "bus",
                "type": "side",
                "address": null
              },
              "geometry": {
                "type": "Point",
                "coordinates": [126.7628366802, 37.4961304007]
              }
            },
            {
              "type": "Feature",
              "properties": {
                "id": 30011496,
                "linkRef": "20001132",
                "laneRef": 3,
                "offset": 65.4,
                "parkingLots": 2,
                "transitMode": "bus",
                "type": "side",
                "address": null
              },
              "geometry": {
                "type": "Point",
                "coordinates": [126.7625645552, 37.4960726120]
              }
            },
            {
              "type": "Feature",
              "properties": {
                "id": 30011497,
                "linkRef": "20001403",
                "laneRef": 2,
                "offset": 42.72,
                "parkingLots": 2,
                "transitMode": "bus",
                "type": "side",
                "address": null
              },
              "geometry": {
                "type": "Point",
                "coordinates": [126.7655181559, 37.4957789094]
              }
            },
            {
              "type": "Feature",
              "properties": {
                "id": 30011498,
                "linkRef": "20001402",
                "laneRef": 2,
                "offset": 40.03,
                "parkingLots": 2,
                "transitMode": "bus",
                "type": "side",
                "address": null
              },
              "geometry": {
                "type": "Point",
                "coordinates": [126.7654899546, 37.4956933427]
              }
            },
            {
              "type": "Feature",
              "properties": {
                "id": 30011502,
                "linkRef": "20001429",
                "laneRef": 2,
                "offset": 29.57,
                "parkingLots": 2,
                "transitMode": "bus",
                "type": "side",
                "address": null
              },
              "geometry": {
                "type": "Point",
                "coordinates": [126.7681945598, 37.4967570727]
              }
            },
            {
              "type": "Feature",
              "properties": {
                "id": 30011503,
                "linkRef": "20001435",
                "laneRef": 2,
                "offset": 0.57,
                "parkingLots": 2,
                "transitMode": "bus",
                "type": "side",
                "address": null
              },
              "geometry": {
                "type": "Point",
                "coordinates": [126.7680847704, 37.4965952399]
              }
            },
            {
              "type": "Feature",
              "properties": {
                "id": 30011504,
                "linkRef": "20001522",
                "laneRef": 2,
                "offset": 37.86,
                "parkingLots": 2,
                "transitMode": "bus",
                "type": "side",
                "address": null
              },
              "geometry": {
                "type": "Point",
                "coordinates": [126.7687037649, 37.4996306751]
              }
            },
            {
              "type": "Feature",
              "properties": {
                "id": 30011505,
                "linkRef": "20001307",
                "laneRef": 1,
                "offset": 94.75,
                "parkingLots": 2,
                "transitMode": "bus",
                "type": "side",
                "address": null
              },
              "geometry": {
                "type": "Point",
                "coordinates": [126.7688376314, 37.4998260860]
              }
            }
          ]
        }',
        'station-test3');
