CREATE TABLE IF NOT EXISTS public.vehicle_route
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    czml jsonb,
    features jsonb,
    insert_date timestamp(6) without time zone,
    positions jsonb,
    version_id character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT vehicle_route_pkey PRIMARY KEY (id)
    )
