server {
    listen 8080;
    server_name localhost;

    location / {
        #add_header 'Access-Control-Allow-Credentials' 'true' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
        add_header 'Access-Control-Allow-Origin' "$http_origin" always; # 동적 출처 반영
        root /usr/share/nginx/html;
        index index.html index.htm;
    }
   location /rest/ {
        client_max_body_size 4096m;
        # 프리플라이트(OPTIONS) 요청 처리
        if ($request_method = OPTIONS) {
                add_header 'Access-Control-Allow-Origin' "$http_origin" always; # 동적 출처 반영
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, DELETE, PUT' always;
                add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization' always;
                add_header 'Access-Control-Allow-Credentials' 'true' always;
                return 204;  # No Content 응답
        }

        # 실제 요청 처리

        proxy_set_header Access-Control-Allow-Credentials 'true';  # 자격 증명 포함
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        rewrite ^/rest/(.*)$ /$1 break;
        proxy_pass http://192.168.10.182:9095;  # 백엔드 서버로 요청 전달

        # 응답 헤더 설정
        add_header 'Access-Control-Allow-Credentials' 'true' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, DELETE, PUT' always;
        add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization' always;
    }
}