/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/vehicle-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getVehicleTypeFlat"];
        put: operations["updateVehicleTypeParameter"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicle-models/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getVehicleTypeFlat_1"];
        put: operations["updateVehicleTypeModel"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menu/{menuId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMenuById"];
        put: operations["updateMenuById"];
        post?: never;
        delete: operations["deleteMenuById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menu/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMenus"];
        put: operations["updateMenus"];
        post: operations["createMenus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicle/vehicle-route/{versionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["getVehicleRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicle/generate-vehicle-route/{versionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["generateVehicleRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicle-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllVehicleTypes"];
        put?: never;
        post: operations["createVehicleTypeWithParameters"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicle-types/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deleteVehicleTypeParameters"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicle-models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllVehicleTypeModel"];
        put?: never;
        post: operations["createVehicleModel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicle-models/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deleteVehicleTypeModels"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/signal/{versionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSignal"];
        put?: never;
        post: operations["saveSignal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schema/{layer-key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSchemaByLayerKey"];
        put?: never;
        post: operations["updateSchemata"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public-transit/station/rail/{versionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRailStationsByVersionId"];
        put?: never;
        post: operations["saveBusStations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public-transit/station/bus/{versionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBusStationsByVersionId"];
        put?: never;
        post: operations["saveBusStations_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pavement-marking/{versionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPavementMarking"];
        put?: never;
        post: operations["savePavementMarking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createMenu"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/signal/origin/{versionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOriginSignal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/signal/histories/{versionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLogsByVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSchemata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllScenarios"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenario/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getScenarioById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenario/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getScenarioVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pavement-marking/origin/{versionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOriginPavementMarking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pavement-marking/histories/{versionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLogsByVersion_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/network/{versionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNetworkByScenarioKey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menu/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMenuTree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menu/depth/{depth}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMenusByDepth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menu/code/{menuCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMenuByCode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layer/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllLayers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layer/group": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllLayerGroup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layer/group/{groupKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLayerGroup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/link-stats/{versionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLinkStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        VehicleTypeModel: {
            /** Format: int64 */
            id?: number;
            name?: string;
            color?: string;
            fileName?: string;
            filePath?: string;
            length?: string;
            /** Format: int64 */
            vehicleTypeId?: number;
            correctionHpr?: string;
            /** Format: double */
            zoffset?: number;
        };
        MenuRequest: {
            /** Format: int64 */
            menuId?: number;
            menuCode?: string;
            language?: string;
            nameKor?: string;
            nameEn?: string;
            /** Format: int64 */
            parentsId?: number;
            /** Format: int64 */
            rootId?: number;
            /** Format: int32 */
            depth?: number;
            /** Format: int32 */
            sortOrder?: number;
            available?: string;
            /** @enum {string} */
            accessRole?: "ROLE_ADMIN" | "ROLE_USER";
        };
        MenuResponse: {
            /** Format: int64 */
            menuId?: number;
            menuCode?: string;
            language?: string;
            nameKor?: string;
            nameEn?: string;
            /** Format: int64 */
            parentsId?: number;
            /** Format: int64 */
            rootId?: number;
            /** Format: int32 */
            depth?: number;
            /** Format: int32 */
            sortOrder?: number;
            available?: string;
            /** @enum {string} */
            accessRole?: "ROLE_ADMIN" | "ROLE_USER";
        };
        Cartesian3: {
            /** Format: double */
            x?: number;
            /** Format: double */
            y?: number;
            /** Format: double */
            z?: number;
        };
        Polyline: {
            positions?: components["schemas"]["Cartesian3"][];
        };
        Road: {
            linkId?: string;
            laneId?: string;
            polyline?: components["schemas"]["Polyline"];
            /** Format: double */
            baseEasting?: number;
            /** Format: double */
            baseNorthing?: number;
            /** Format: double */
            targetEasting?: number;
            /** Format: double */
            targetNorthing?: number;
            /** Format: double */
            halfWidth?: number;
        };
        RoadResponse: {
            roads?: components["schemas"]["Road"][];
        };
        VehicleRequest: {
            /** Format: int32 */
            numVehicle?: number;
            roadEntities?: components["schemas"]["RoadResponse"];
            /** Format: int32 */
            speedFactor?: number;
        };
        Detail: {
            field?: string;
            newValue?: unknown;
            oldValue?: unknown;
            guid?: string;
            timestamp?: string;
        };
        LogsData: {
            added?: components["schemas"]["Detail"][];
            deleted?: components["schemas"]["Detail"][];
            modified?: components["schemas"]["Detail"][];
        };
        SignalResponse: {
            nodeId?: string;
            turnId?: string;
            turning?: string;
            type?: string;
            connectionId?: string;
        };
        SignalSaveRequest: {
            data?: components["schemas"]["SignalResponse"][];
            logs?: components["schemas"]["LogsData"];
        };
        CreateFieldOptionRequest: {
            value?: string;
        };
        CreateFieldRequest: {
            name?: string;
            nullable?: boolean;
            defaultValue?: string;
            readOnly?: boolean;
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE" | "DELETED";
            inputType?: string;
            options?: components["schemas"]["CreateFieldOptionRequest"][];
        };
        SchemaFieldsRequest: {
            /** Format: int64 */
            id?: number;
            fieldsToCreate?: components["schemas"]["CreateFieldRequest"][];
            fieldsToUpdate?: components["schemas"]["UpdateFieldRequest"][];
            fieldIdsToDelete?: number[];
        };
        UpdateFieldOption: {
            /** Format: int64 */
            id?: number;
            value?: string;
        };
        UpdateFieldRequest: {
            /** Format: int64 */
            id?: number;
            name?: string;
            nullable?: boolean;
            defaultValue?: string;
            readOnly?: boolean;
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE" | "DELETED";
            inputType?: string;
            options?: components["schemas"]["UpdateFieldOption"][];
            optionsToCreate?: components["schemas"]["CreateFieldOptionRequest"][];
            optionIdsToDelete?: number[];
        };
        Coordinates: {
            /** Format: double */
            lat?: number;
            /** Format: double */
            lng?: number;
        };
        ExitData: {
            id?: string;
            /** Format: int32 */
            linkRef?: number;
            /** Format: double */
            offset?: number;
            /** Format: double */
            accessTime?: number;
            coord?: string;
        };
        RailStationData: {
            id?: string;
            transitMode?: string;
            address?: string;
            center?: string;
            exits?: components["schemas"]["ExitData"][];
            timetables?: components["schemas"]["TimetableData"][];
            lineList?: string[];
            coordinates?: components["schemas"]["Coordinates"];
        };
        RailStationSaveRequest: {
            /** Format: date-time */
            timestamp?: string;
            data?: components["schemas"]["RailStationData"][];
            logs?: components["schemas"]["LogsData"];
        };
        TimetableData: {
            dayOfWeek?: string;
            lineId?: string;
            times?: string[];
        };
        BusStationData: {
            id?: string;
            transitMode?: string;
            /** Format: int32 */
            linkRef?: number;
            /** Format: int32 */
            laneRef?: number;
            /** Format: double */
            pos?: number;
            type?: string;
            /** Format: int32 */
            parkingLots?: number;
            address?: string;
            center?: string;
            lines?: string[];
        };
        BusStationSaveRequest: {
            data?: components["schemas"]["BusStationData"][];
            logs?: components["schemas"]["LogsData"];
        };
        PavementMarkingData: {
            id?: string;
            /** Format: double */
            angle?: number;
            /** Format: int32 */
            cellId?: number;
            /** Format: double */
            offset?: number;
            /** Format: int32 */
            laneRef?: number;
            /** Format: int32 */
            linkRef?: number;
            markingType?: string;
            coordinates?: components["schemas"]["Coordinates"][];
        };
        PavementMarkingSaveRequest: {
            data?: components["schemas"]["PavementMarkingData"][];
            logs?: components["schemas"]["LogsData"];
        };
        VehicleType: {
            /** Format: int64 */
            id?: number;
            vehicleId?: string;
            name?: string;
            v2x?: string;
            drt?: string;
            maxPax?: string;
        };
        SignalNodeResponseData: {
            signals?: components["schemas"]["SignalResponse"][];
        };
        SignalLogs: {
            versionId?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: int64 */
            id?: number;
            data?: components["schemas"]["LogsData"];
        };
        ColumnOption: {
            value?: string;
        };
        LayerSchemaFieldResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            inputType?: string;
            defaultValue?: string;
            readOnly?: boolean;
            nullable?: boolean;
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE" | "DELETED";
            options?: components["schemas"]["LayerSchemaOptionResponse"][];
        };
        LayerSchemaOptionResponse: {
            /** Format: int64 */
            id?: number;
            value?: string;
        };
        LayerSchemaResponse: {
            /** Format: int64 */
            layerId?: number;
            layerName?: string;
            schemaColumns?: components["schemas"]["SchemaColumn"][];
            definition?: components["schemas"]["SchemaDefinition"][];
            structure?: components["schemas"]["SchemaStructure"][];
        };
        SchemaColumn: {
            configKey?: string;
            inputType?: string;
            options?: components["schemas"]["ColumnOption"][];
        };
        SchemaDefinition: {
            /** Format: int64 */
            id?: number;
            name?: string;
            status?: string;
            fields?: components["schemas"]["LayerSchemaFieldResponse"][];
        };
        SchemaStructure: {
            name?: string;
            children?: components["schemas"]["SchemaStructure"][];
        };
        Scenario: {
            /** Format: int64 */
            id?: number;
            key?: string;
            /** Format: double */
            longitude?: number;
            /** Format: double */
            latitude?: number;
            label?: string;
            description?: string;
            versions?: components["schemas"]["ScenarioVersion"][];
        };
        ScenarioVersion: {
            /** Format: int64 */
            id?: number;
            key?: string;
            label?: string;
            /** Format: date-time */
            insertDate?: string;
            /** Format: date-time */
            modifyDate?: string;
        };
        ExitResponse: {
            id?: string;
            linkRef?: string;
            /** Format: double */
            offset?: number;
            accessTime?: string;
            coord?: string;
        };
        RailPublicTransitResponse: {
            railStations?: components["schemas"]["RailStationResponse"][];
        };
        RailStationResponse: {
            id?: string;
            /** @enum {string} */
            transitMode?: "subway" | "bus";
            lineList?: string;
            /** @enum {string} */
            type?: "island" | "side" | "face_to_face" | "staggered";
            address?: string;
            center?: string;
            exits?: components["schemas"]["ExitResponse"][];
            coordinates?: components["schemas"]["Coordinates"];
        };
        BusLineResponse: {
            list?: string;
        };
        BusStationResponse: {
            id?: string;
            /** @enum {string} */
            transitMode?: "subway" | "bus";
            /** Format: int64 */
            linkRef?: number;
            /** Format: int64 */
            laneRef?: number;
            /** Format: double */
            offset?: number;
            /** @enum {string} */
            type?: "island" | "side" | "face_to_face" | "staggered";
            /** Format: int32 */
            parkingLots?: number;
            address?: string;
            center?: string;
            line?: components["schemas"]["BusLineResponse"];
        };
        PublicTransitResponse: {
            busStations?: components["schemas"]["BusStationResponse"][];
        };
        RoadAssetData: {
            pavementMarkings?: components["schemas"]["PavementMarkingData"][];
        };
        PavementMarkingLogs: {
            versionId?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: int64 */
            id?: number;
            data?: components["schemas"]["LogsData"];
        };
        CellResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: double */
            length?: number;
            /** Format: double */
            offset?: number;
        };
        ConnectionResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            fromLink?: number;
            /** Format: int64 */
            fromLane?: number;
            /** Format: int64 */
            toLink?: number;
            /** Format: int64 */
            toLane?: number;
            /** @enum {string} */
            turning?: "Straight" | "Right_Turn" | "Left_Turn";
            /** Format: double */
            length?: number;
            /** Format: double */
            width?: number;
            /** Format: double */
            ffSpd?: number;
            shape?: string;
        };
        LaneResponse: {
            /** Format: int64 */
            id?: number;
            leftLaneId?: string;
            rightLaneId?: string;
            /** Format: int32 */
            numCell?: number;
            laneAccessType?: string;
            rightLC?: boolean;
            leftLC?: boolean;
            shape?: string;
            segments?: components["schemas"]["SegmentResponse"][];
            cells?: components["schemas"]["CellResponse"][];
        };
        LinkResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            fromNode?: number;
            /** Format: int64 */
            toNode?: number;
            /** Format: int32 */
            numLane?: number;
            /** Format: double */
            length?: number;
            /** Format: double */
            width?: number;
            /** Format: double */
            maxSpd?: number;
            /** Format: double */
            minSpd?: number;
            /** Format: double */
            ffSpd?: number;
            /** Format: double */
            waveSpd?: number;
            /** Format: double */
            qmax?: number;
            /** Format: double */
            maxVeh?: number;
            /** @enum {string} */
            simType?: "Meso" | "Micro";
            /** @enum {string} */
            type?: "straight" | "curve";
            layer?: string;
            /** Format: double */
            stopLine?: number;
            shape?: string;
            lanes?: components["schemas"]["LaneResponse"][];
            sections?: components["schemas"]["SectionResponse"][];
            coordinates?: components["schemas"]["Coordinates"][];
        };
        NetworkResponse: {
            nodes?: components["schemas"]["NodeResponse"][];
            links?: components["schemas"]["LinkResponse"][];
        };
        NodeResponse: {
            /** Format: int64 */
            id?: number;
            /** @enum {string} */
            type?: "Intersection" | "Normal" | "Merging" | "Diverging" | "Terminal" | "Garage";
            /** Format: int32 */
            numPort?: number;
            /** Format: int32 */
            numConnection?: number;
            /** @enum {string} */
            v2x?: "on" | "off";
            center?: string;
            ports?: components["schemas"]["PortResponse"][];
            connections?: components["schemas"]["ConnectionResponse"][];
            coordinates?: components["schemas"]["Coordinates"];
            portLinkIds?: string[];
        };
        PortResponse: {
            /** @enum {string} */
            type?: "in" | "out";
            linkId?: string;
            /** Format: int64 */
            direction?: number;
        };
        SectionResponse: {
            /** Format: int64 */
            id?: number;
            leftId?: string;
            rightId?: string;
            /** Format: double */
            slope?: number;
            /** Format: double */
            length?: number;
            /** Format: double */
            offset?: number;
        };
        SegmentResponse: {
            /** Format: int64 */
            id?: number;
            block?: boolean;
            /** Format: double */
            initPoint?: number;
            /** Format: double */
            endPoint?: number;
        };
        MenuTreeResponse: {
            /** Format: int64 */
            menuId?: number;
            menuCode?: string;
            language?: string;
            nameKor?: string;
            nameEn?: string;
            /** Format: int32 */
            depth?: number;
            /** Format: int32 */
            sortOrder?: number;
            available?: string;
            /** @enum {string} */
            accessRole?: "ROLE_ADMIN" | "ROLE_USER";
            children?: components["schemas"]["MenuTreeResponse"][];
            /** Format: int64 */
            rootId?: number;
        };
        LayerResponse: {
            /** Format: int64 */
            id?: number;
            key?: string;
            label?: string;
            basic?: boolean;
            /** Format: int32 */
            auth?: number;
            formType?: string;
            url?: string;
            groupKey?: string;
        };
        LayerGroupResponse: {
            /** Format: int64 */
            id?: number;
            key?: string;
            label?: string;
            layers?: components["schemas"]["LayerResponse"][];
        };
        LinkStatsResponse: {
            /** Format: int32 */
            interval?: number;
            overallTimeSeries?: components["schemas"]["TimeSlotStats"][];
            topLinks?: components["schemas"]["LinkSummary"][];
        };
        LinkSummary: {
            linkId?: string;
            /** Format: int32 */
            totalVolume?: number;
            /** Format: double */
            avgSpeed?: number;
            timeSeries?: components["schemas"]["TimeSlotStats"][];
        };
        TimeSlotStats: {
            /** Format: int32 */
            time?: number;
            /** Format: int32 */
            volume?: number;
            /** Format: double */
            avgSpeed?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type VehicleTypeModel = components['schemas']['VehicleTypeModel'];
export type MenuRequest = components['schemas']['MenuRequest'];
export type MenuResponse = components['schemas']['MenuResponse'];
export type Cartesian3 = components['schemas']['Cartesian3'];
export type Polyline = components['schemas']['Polyline'];
export type Road = components['schemas']['Road'];
export type RoadResponse = components['schemas']['RoadResponse'];
export type VehicleRequest = components['schemas']['VehicleRequest'];
export type Detail = components['schemas']['Detail'];
export type LogsData = components['schemas']['LogsData'];
export type SignalResponse = components['schemas']['SignalResponse'];
export type SignalSaveRequest = components['schemas']['SignalSaveRequest'];
export type CreateFieldOptionRequest = components['schemas']['CreateFieldOptionRequest'];
export type CreateFieldRequest = components['schemas']['CreateFieldRequest'];
export type SchemaFieldsRequest = components['schemas']['SchemaFieldsRequest'];
export type UpdateFieldOption = components['schemas']['UpdateFieldOption'];
export type UpdateFieldRequest = components['schemas']['UpdateFieldRequest'];
export type Coordinates = components['schemas']['Coordinates'];
export type ExitData = components['schemas']['ExitData'];
export type RailStationData = components['schemas']['RailStationData'];
export type RailStationSaveRequest = components['schemas']['RailStationSaveRequest'];
export type TimetableData = components['schemas']['TimetableData'];
export type BusStationData = components['schemas']['BusStationData'];
export type BusStationSaveRequest = components['schemas']['BusStationSaveRequest'];
export type PavementMarkingData = components['schemas']['PavementMarkingData'];
export type PavementMarkingSaveRequest = components['schemas']['PavementMarkingSaveRequest'];
export type VehicleType = components['schemas']['VehicleType'];
export type SignalNodeResponseData = components['schemas']['SignalNodeResponseData'];
export type SignalLogs = components['schemas']['SignalLogs'];
export type ColumnOption = components['schemas']['ColumnOption'];
export type LayerSchemaFieldResponse = components['schemas']['LayerSchemaFieldResponse'];
export type LayerSchemaOptionResponse = components['schemas']['LayerSchemaOptionResponse'];
export type LayerSchemaResponse = components['schemas']['LayerSchemaResponse'];
export type SchemaColumn = components['schemas']['SchemaColumn'];
export type SchemaDefinition = components['schemas']['SchemaDefinition'];
export type SchemaStructure = components['schemas']['SchemaStructure'];
export type Scenario = components['schemas']['Scenario'];
export type ScenarioVersion = components['schemas']['ScenarioVersion'];
export type ExitResponse = components['schemas']['ExitResponse'];
export type RailPublicTransitResponse = components['schemas']['RailPublicTransitResponse'];
export type RailStationResponse = components['schemas']['RailStationResponse'];
export type BusLineResponse = components['schemas']['BusLineResponse'];
export type BusStationResponse = components['schemas']['BusStationResponse'];
export type PublicTransitResponse = components['schemas']['PublicTransitResponse'];
export type RoadAssetData = components['schemas']['RoadAssetData'];
export type PavementMarkingLogs = components['schemas']['PavementMarkingLogs'];
export type CellResponse = components['schemas']['CellResponse'];
export type ConnectionResponse = components['schemas']['ConnectionResponse'];
export type LaneResponse = components['schemas']['LaneResponse'];
export type LinkResponse = components['schemas']['LinkResponse'];
export type NetworkResponse = components['schemas']['NetworkResponse'];
export type NodeResponse = components['schemas']['NodeResponse'];
export type PortResponse = components['schemas']['PortResponse'];
export type SectionResponse = components['schemas']['SectionResponse'];
export type SegmentResponse = components['schemas']['SegmentResponse'];
export type MenuTreeResponse = components['schemas']['MenuTreeResponse'];
export type LayerResponse = components['schemas']['LayerResponse'];
export type LayerGroupResponse = components['schemas']['LayerGroupResponse'];
export type LinkStatsResponse = components['schemas']['LinkStatsResponse'];
export type LinkSummary = components['schemas']['LinkSummary'];
export type TimeSlotStats = components['schemas']['TimeSlotStats'];
export type $defs = Record<string, never>;
export interface operations {
    getVehicleTypeFlat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    updateVehicleTypeParameter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    getVehicleTypeFlat_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    updateVehicleTypeModel: {
        parameters: {
            query?: {
                name?: string;
                vehicleTypeId?: number;
                color?: string;
                length?: string;
                correctionHpr?: string;
                zOffset?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VehicleTypeModel"];
                };
            };
        };
    };
    getMenuById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                menuId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MenuResponse"];
                };
            };
        };
    };
    updateMenuById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                menuId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MenuRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MenuResponse"];
                };
            };
        };
    };
    deleteMenuById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                menuId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMenus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MenuResponse"][];
                };
            };
        };
    };
    updateMenus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MenuResponse"][];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MenuResponse"][];
                };
            };
        };
    };
    createMenus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MenuRequest"][];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MenuResponse"][];
                };
            };
        };
    };
    getVehicleRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    generateVehicleRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VehicleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getAllVehicleTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VehicleType"][];
                };
            };
        };
    };
    createVehicleTypeWithParameters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    deleteVehicleTypeParameters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": number[];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    getAllVehicleTypeModel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VehicleTypeModel"][];
                };
            };
        };
    };
    createVehicleModel: {
        parameters: {
            query?: {
                name?: string;
                vehicleTypeId?: number;
                color?: string;
                length?: string;
                correctionHpr?: string;
                zOffset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    deleteVehicleTypeModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": number[];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    getSignal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SignalNodeResponseData"];
                };
            };
        };
    };
    saveSignal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignalSaveRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSchemaByLayerKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                "layer-key": string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LayerSchemaResponse"];
                };
            };
        };
    };
    updateSchemata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                "layer-key": string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SchemaFieldsRequest"][];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getRailStationsByVersionId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RailPublicTransitResponse"];
                };
            };
        };
    };
    saveBusStations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RailStationSaveRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getBusStationsByVersionId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PublicTransitResponse"];
                };
            };
        };
    };
    saveBusStations_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BusStationSaveRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPavementMarking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoadAssetData"];
                };
            };
        };
    };
    savePavementMarking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PavementMarkingSaveRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createMenu: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MenuRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MenuResponse"];
                };
            };
        };
    };
    getOriginSignal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SignalNodeResponseData"];
                };
            };
        };
    };
    getLogsByVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SignalLogs"][];
                };
            };
        };
    };
    getSchemata: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LayerSchemaResponse"][];
                };
            };
        };
    };
    getAllScenarios: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Scenario"][];
                };
            };
        };
    };
    getScenarioById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Scenario"];
                };
            };
        };
    };
    getScenarioVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScenarioVersion"][];
                };
            };
        };
    };
    getOriginPavementMarking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoadAssetData"];
                };
            };
        };
    };
    getLogsByVersion_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PavementMarkingLogs"][];
                };
            };
        };
    };
    getNetworkByScenarioKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NetworkResponse"];
                };
            };
        };
    };
    getMenuTree: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MenuTreeResponse"][];
                };
            };
        };
    };
    getMenusByDepth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                depth: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MenuResponse"][];
                };
            };
        };
    };
    getMenuByCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                menuCode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MenuResponse"];
                };
            };
        };
    };
    getAllLayers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LayerResponse"][];
                };
            };
        };
    };
    getAllLayerGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LayerGroupResponse"][];
                };
            };
        };
    };
    getLayerGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LayerGroupResponse"];
                };
            };
        };
    };
    getLinkStats: {
        parameters: {
            query?: {
                interval?: number;
                topN?: number;
            };
            header?: never;
            path: {
                versionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LinkStatsResponse"];
                };
            };
        };
    };
}
